# Generated by Django 2.2.5 on 2021-02-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarShopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='price',
            field=models.IntegerField(verbose_name=20),
        ),
    ]
