# Generated by Django 2.2.5 on 2021-02-09 20:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarShopping', '0003_auto_20210205_1419'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guitar',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='guitar',
            old_name='model_name',
            new_name='guitar_name',
        ),
        migrations.AddField(
            model_name='guitar',
            name='model_choice',
            field=models.CharField(default='', max_length=30),
        ),
    ]
