# Generated by Django 2.2.5 on 2021-02-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarShopping', '0004_auto_20210209_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='guitar_name',
        ),
    ]
