# Generated by Django 2.2.5 on 2021-02-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuitarShopping', '0005_remove_guitar_guitar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
